### PR TITLE
Fix nDCG for result count < k

### PR DESCRIPTION
**Pull request by rudibatt**
Fix score for results with hitCount<k by simplifying padding of missing docs & missing ratings

## Description
For some reason the nDCG score for products with a hitCount below 10 (K) was always 0. 
I could fix it by making a simple old fashioned loop to pad the "ideal" and "scores" array.

## How Has This Been Tested?
On my internal installation.

## Screenshots or GIFs (if appropriate):
grafik

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (Searched for, not found)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by epugh** [comment]
@nathancday @binarymax I would feel much better if either (or both!) would review this PR for me.

**Comment by binarymax** [comment]
I approve @epugh!  I'm not a reviewer though and I'll let you merge.  Thanks so much @rudibatt !!!

**Review by nathancday — APPROVED** [review]
Looks good, thanks for cleaning up the bugs.

**Comment by epugh** [comment]
Thanks @rudibatt for this...   I need to add a migration so that users with already deployed Quepid's get this new script loaded into the database.     We *just* had this bug reported in one of our _TLRE_ classes, and you showed up with the fix!

**Pull request merged**
