### PR TITLE
Add openid support

### PR DESCRIPTION
**Pull request by epugh**
## Description
Leverages the Devise support of `:omniauthable` to add Omniauth, which means we can add more auth strategies, which opened the door to adding `omniauth-keycloak` which does OpenID via Keycloak.  

## Motivation and Context

We assume that Quepid manages it's own users, as that is what happens on the hosted app...   But in many places you don't want Yet Another User Account...   So this is a baby step towards that.

There was an issue opened #188 about this!

I'm putting this up primarily as a spike, hoping others will help me test it all out.   Things that are needed:

- [ ]  A test of some variety!   Would be nice to have a test of this path.
- [x] A way of swapping open id providers.  I went with Keycloak, because I am using it on the Chorus project.  Others should be easily added.   Maybe just some documentation on how to do it?
- [ ]  Logout button doesn't connect to keycloak
- [ ]  We still show the edit password and other profile edit features, we should link out instead.

## How Has This Been Tested?

Manual testing using this PR in Chorus: https://github.com/querqy/chorus/pull/47

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by epugh** [comment]
@gregoryduckworth I'd love some help pushing this PR forward if you wanted?  I think you are interested in adding Github...   Maybe we can add a couple of common strategies and have a environment variable or something?  We need to update the UI to support this!

**Comment by gregoryduckworth** [comment]
> @gregoryduckworth I'd love some help pushing this PR forward if you wanted? I think you are interested in adding Github... Maybe we can add a couple of common strategies and have a environment variable or something? We need to update the UI to support this!

Sorry it has taken so long getting back to you on this. I'll take a look at this over the coming week or so.

**Comment by epugh** [comment]
That's great...    Right now i've got Keycloak hard coded in the footer to be the auth tool..    I haven't actually thought through what it would take to let Quepid auth against any openid server...    

I do want to change up the login page to be a regular HTML/Rails page, and get rid of the Angular app (`secure.js`) since there isn't any need for that.   Then, think about how to make it easy to run open id against various other providers.

I'd love your input..  I know I want to add Keycloak (to make Quepid auth with the same provider as other tools in Chorus stack), however I'd like it to auth against whatever openid server you wanted!

**Comment by epugh** [comment]
Screenshot at May 24 15-36-34

I circled back to this, and now have Google Auth and what I'm calling OpenId, but is really Keycloak, working.....    I am not sure what to say...  "Sign in with Keycloak"??  

I also haven't figured out how to programmatically enabled/disable them!

**Comment by epugh** [comment]
@gregoryduckworth i wanted to ping you one more time, as this is finally getting close to shipping, so I'd love any feedback before it goes live ;-)   Happy to jump on a Zoom with you if useful.   Demo site is at http://quepid-pr-280.herokuapp.com

**Comment by gregoryduckworth** [comment]
Thank you for all your work @epugh on this, I'll try it out today!

**Comment by epugh** [comment]
> Thank you for all your work @epugh on this, I'll try it out today!

Great.  THe preview version only has Google Auth enabled, however I also have Keycloak (https://www.keycloak.org/) if you are running the local developer version.   I'm hoping that we can find an easy way to introduce other oAuth providers that folks might want to run.

**Comment by gregoryduckworth** [comment]
All looks good to me @epugh 👍  for the work!

**Pull request merged**
