### PR TITLE
Human judgements part deux

### PR DESCRIPTION
**Pull request by epugh**
## Description
Some more clean up and making the card metaphor stronger

## Motivation and Context
Stealing more ideas from discernatron

## How Has This Been Tested?
manually

## Types of changes

### CODE REVIEW

**Comment by epugh** [comment]
@DmitryKey here are some more UX fixes to the human rating screen ;-)

**Comment by DmitryKey** [comment]
Cool! Are these available on the heroku staging?

**Comment by epugh** [comment]
yep...

**Comment by epugh** [comment]
Just did an internal demo with my OSC people, and got a couple more fixes coming.  Part Trois ;-)

**Pull request merged**
