### PR TITLE
fix for #979

### PR DESCRIPTION
**Pull request by epugh**
## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by epugh** [comment]
@reid-rigo I'm going to merge this PR as a hotfix, however, I'd love your thoughts on if this fix is "the right" fix!

**Comment by epugh** [comment]
Argh..   lots of errors....  Now I remember why i disliked "distinct"...

```
Listing cases#test_does_not_return_archived_cases_by_default (36.11s)
Minitest::UnexpectedError:         RuntimeError: Neutered Exception ActionView::Template::Error: Mysql2::Error: Expression #1 of ORDER BY clause is not in SELECT list, references column 'quepid_test.case_metadata.last_viewed_at' which is not in SELECT list; this is incompatible with DISTINCT
            app/views/api/v1/cases/index.json.jbuilder:4
            app/views/api/v1/cases/index.json.jbuilder:3
            app/controllers/api/v1/cases_controller.rb:69:in `index'
            test/controllers/api/v1/cases_controller_test.rb:471:in `block (2 levels) in <class:CasesControllerTest>'
```

**Comment by epugh** [comment]
I hate that this generates two queries!   But...

**Comment by reid-rigo** [comment]
Huh, thanks for fixing this. It looks like this is needed for that `order`:

```diff
diff --git a/app/controllers/api/v1/cases_controller.rb b/app/controllers/api/v1/cases_controller.rb
index a92be2d4..844b5548 100644
--- a/app/controllers/api/v1/cases_controller.rb
+++ b/app/controllers/api/v1/cases_controller.rb
@@ -62,6 +62,7 @@ module Api
                      current_user.cases_involved_with.not_archived.with_counts.preload(:tries, :teams,
                                                                                        :cases_teams)
                        .left_outer_joins(:metadata)
+                       .select('cases.*, case_metadata.last_viewed_at')
                        .order(Arel.sql('`case_metadata`.`last_viewed_at` DESC, `cases`.`updated_at` DESC'))
                    end
         end
```

**Pull request merged**
