### PR TITLE
Support auto-complete also for fields used with thumb: prefix

### PR DESCRIPTION
**Pull request by moshebla**
Also make the fields lookup case and whitespace insensitive

I also wanted to make it to select the full field name on enter (currently adds the typed string, and not the full auto-completed field). Might look into that later unless you have an idea.

### CODE REVIEW

**Comment by epugh** [comment]
going to check this out..  I wonder when we should start writing unit tests for this stuff....

**Comment by epugh** [comment]
@moshebla I got side tracked with #48 and didn't get to finish testing this one.   If you get a chance to augment the unit tests, that would be great.   It make take me a bit to grok this code flow ;-)

**Comment by moshebla** [comment]
@epugh sure, can you point me at where the tests for the wizard controller are? couldn't find any

**Comment by epugh** [comment]
I believe this is the right place:

https://github.com/o19s/quepid/blob/master/spec/javascripts/angular/controllers/wizardModal_spec.js

Thanks and happy new year!

**Comment by epugh** [comment]
@moshebla I wanted to let you know I'm attempting to add a test to `wizardModel_spec.js` but am not having much luck...   Let me know if you have more luck! 

```
    it ('lists fields for autocomplete', function() {
      console.log("Running the test");
      expect(true).toBe(true);

      scope.searchFields = ["title","body","image"];

      console.log("Here we go");
      console.log(WizardModalCtrl);

      var autocompleteList = WizardModalCtrl.loadFields("title");

      console.log(autocompleteList);
      expect(autocompleteList.length).toBe(1);

    });
```

**Comment by epugh** [comment]
This looks great, thanks @moshebla and @worleydl

**Pull request merged**
