### PR TITLE
Rails 5 upgrade

### PR DESCRIPTION
**Pull request by epugh**
## Description
Bump rails

## Motivation and Context
Rails 5 had a bug patch to fix a GPL/MIT licensing issue in mimetype handling.

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by DmitryKey** [comment]
Found one issue:

created 2 cases, added a query to one, rated results. In the cases list seeing, that "Last Run On" = "Never Run":

Screenshot 2021-03-27 at 21 41 54

**Comment by DmitryKey** [comment]
Also Last Score is not reflected, but visible on the case: 
Screenshot 2021-03-27 at 21 43 08

**Comment by epugh** [comment]
digging into this now...   I love that the example you created is in our shared staging db so I can look there and see whats going on...

**Comment by epugh** [comment]
The downside of having @DmitryKey test my code...    he finds bugs...!!!    I think we may NOT be properly storing the last score in the `cases_scores` table!   Ack...

**Comment by epugh** [comment]
We say we send the score information back to the API:

```
$log.info('sending score information to mothership');
caseSvc.trackLastScore(caseNo, lastScoreTracker);
```

But nothing ever happens!

**Comment by epugh** [comment]
Yep, so the bad news is in prod on app.quepid.com we haven't tracked scores since `2021-03-05 15:03:03`.   This probably crept in when I was fighting the perofrmance issues....

**Comment by epugh** [comment]
Okay, I created https://github.com/o19s/quepid/issues/306 to track this....

**Pull request merged**
