### PR TITLE
WIP: Adding support for Solr Json queries

### PR DESCRIPTION
**Pull request by moshebla**
We are working with the Solr Json query API and need to have such support in Quepid.

This PR adds the option of choosing whether the request is query-string only, or has Json body as well. The UI was changed to show the following (adding checkboxes for choosing query type, and allowing side-by-side JSON editor and query string editor):

Screenshot_2019-12-12_11-28-35

Screenshot_2019-12-12_11-27-41

This PR depends on this splainer-search PR: https://github.com/o19s/splainer-search/pull/73

Still WIP as we need to get the splainer-search changes in. Once they are merged in and the splainer package updated in Quepid, I will need your help in figuring out how to pass the Json string instead of queryParams - there's a bit too much magic going on and I wasn't able to track it all down.

Comments welcome!

### CODE REVIEW

**Comment by moshebla** [comment]
@epugh did you get a chance to review this at least on a basic level, to make sure I'm in the right direction so once the splainer PR gets merged we can move forward with this one?

**Comment by o19s-admin** [comment]
Thanks for the nudge and I will follow up tomorrow.   Did you see Dougs
comment?

**Comment by moshebla** [comment]
Yes, not sure how actionable it is. I responded there.

**Comment by epugh** [comment]
@moshebla did the revamped plan of supporting Solr JSON queries via having a separate Solr in http://github.com/o19s/splainer-search make sense?     So we'll have Elasticsearch and then  SolrClassic and SolrJSON as the searchers that splainer-search and therefore Quepid would support?   I wanted to make sure that plan makes sense, and then I'll close this PR in favour of that approach.

**Comment by epugh** [comment]
I'm going to close this PR, since the direction we want to go is having a third "type" of search engine, which is the Solr JSON.   So Solr Classic and Solr JSON.    Any contributions in that directions @moshebla will be *very* much appreciated, and this PR was useful for @softwaredoug and I to think thorugh the direction to go.

**Comment by adfel70** [comment]
We find Quepid as a a great tool through our entire product's life cycle, but as we are moving on to Solr json DSL we cant use it any more. Is there any way to promote this issue?

**Pull request closed without merging**
