### PR TITLE
Issue-585: Adding notebook for calculating Jaccard Similarity Index

### PR DESCRIPTION
**Pull request by atarora**
## Description
Adding a notebook to process snapshot data and calculate Jaccard Similarity between 2 snapshots for the purpose of regression and improvements

## Motivation and Context

#585 

## How Has This Been Tested?

Please see the screenshot

## Screenshots or GIFs (if appropriate):
Screenshot 2022-12-15 at 16 03 27

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by epugh** [comment]
I am going to see if our "Branch deploy" strategy properly picks up this notebook and deploys it.....

**Comment by epugh** [comment]
I loved that I could navigate to the actual dashboard, https://github.com/o19s/quepid/blob/issue_585/jupyterlite/files/examples/Snapshot%20Jaccard.ipynb and check it out...

So one thought I had is that if this is going to be a default example that lots of users will base their own Jaccard on, should we redo this one and point to the tmdb dataset instead?

**Comment by atarora** [comment]
@epugh please review after the changes as per the feedback.

**Comment by epugh** [comment]
this looks great...  one last question, is it possible to sum up the jaccards at the query level to have it at the case level?

**Comment by epugh** [comment]
I like I can view the notebook right in github by view file ;-)

**Comment by atarora** [comment]
I updated the notebook to reflect mean of column jaccard_similarity. Does that helps ?

**Comment by epugh** [comment]
LGTM.  I will try and deploy it to produciton maybe tomorrow/

**Review by epugh — APPROVED** [review]

**Comment by epugh** [comment]
I have been struggling to get jupyterlite to run on my http://localhost:3000, how it runs on stage just fine...   so...  Going to merge this and then test on STaging

**Pull request merged**
