### PR TITLE
Quepid, why can't you be more like Discernatron?

### PR DESCRIPTION
**Pull request by epugh**
## Description
Collect multiple ratings.  For the front end, just average out the scores (for now).

## Motivation and Context
Any robust human judgement program will have multiple ratings per query/doc combination.   Today, Quepid only supports a single rating, and we're all updating it at the same time.  

The only open source tool out there that supports this is https://github.com/wikimedia/wikimedia-discovery-discernatron, and it's very tied to the WMF ecosystem.   Though this does suggest I should poke again at it and confirm it won't run standalone!

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by epugh** [comment]
discernatron 7 07 39 PM

**Comment by epugh** [comment]
@worleydl I realized that I have left this in a slightly undone state when I started refacotring the otehr day.  https://quepid-pr-263.herokuapp.com/ won't fire up..  

Working on it ;-)

**Comment by epugh** [comment]
Went through a demo with @DmitryKey and @eribeiro of this.   We are on the right track, @epugh needs to fix up some code that he broke, make sure the UI changes between individual and group views.    @DmitryKey is going to look at @binarymax JarJar project https://github.com/o19s/jarjar.    

https://haystackconf.com/2019/human-judgement/
https://www.youtube.com/watch?v=7PjBSH6Wqhc&list=PLCoJWKqBHERu9Fe0W12D7XKwGT2eoJJNU&index=5
https://www.youtube.com/watch?v=lG7DGMgfOb8

**Comment by epugh** [comment]
Here is a talk that @DmitryKey and  I did: https://www.youtube.com/watch?v=_CBl2aWuJiI

**Comment by epugh** [comment]
Here is Discernatron, though not the fun "card" interface ;-)
https://wikimedia-research.github.io/Discovery-Search-Adhoc-RelevanceSurveys/figures/example_discernatron.png

**Comment by DmitryKey** [comment]
So much color in it -- I got hungry just by staring at the table :)
What is your thought for this in Quepid?

**Comment by epugh** [comment]
The two things that Dicernatron had that Quepid doesn't is 1) Multiple Raters, and 2) the optimized Rating interface....    Mostly wanted to document the screenshot for posterity.   

Honestly, I've run a bit out of steam on the multiple rater support, maybe because of the lack of a Optimized Rating Interface to drive the need for Multiple Rater support?

**Comment by DmitryKey** [comment]
Yes, I think that adding Multiple Raters should be driven by us finalizing the math behind it. For instance, implement cross-annotator agreement calculation and, perhaps, allow for js-based syntax for custom functions, like with Scorers.
WDYT?

It will be just a building block on the way of forming our vision for multi-rater feature.

**Pull request closed without merging**
