### PR TITLE
Feature/sort by modified try2

### PR DESCRIPTION
**Pull request by DmitryKey**
Introduced Modified sort option on the case page -- this PR requires more work, because I'm not entirely sure how to make the js part to work.
This branch is on top of `master`.
## Motivation and Context

#307 

## How Has This Been Tested?
Testing so far was manual.

## Screenshots or GIFs (if appropriate):
Screenshot 2021-05-02 at 11 20 45

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by DmitryKey** [comment]
The screenshot above was taken with this PR atop https://github.com/o19s/quepid/tree/spike_adding_multiple_raters.
This screenshot is same PR atop master:
Screenshot 2021-05-02 at 14 35 11

@epugh @binarymax Notice the difference?

**Comment by DmitryKey** [comment]
Hm, I wonder if DB is compatible across `master` and `spike_adding_multiple_raters` branches?

**Comment by epugh** [comment]
I think you are rihgt.  in `spike_adding_multiple_raters` we add to the the `ratings` table a `user_id` column...    And unforutnantly, the way I have staging and the review apps set up, they all use the same schema.    I need to take a stab at seperating out the databases.

I'll poke at your code, and see if I can't add the server side....   probbly on monday.

**Comment by DmitryKey** [comment]
@epugh does this PR need more JS fixes, looking at the CI output?

**Comment by epugh** [comment]
good question @DmitryKey...    I think, because I touched the test, that DeepSource is now looking at it..   I guess I'll fix it!

**Pull request merged**
