### PR TITLE
add new env flag to allow query list to be unsortable

### PR DESCRIPTION
**Pull request by LiuCao0614**
## Description

Add a new env flag that if set to false query list are unsortable. 

## Motivation and Context

This mr provides a workaround for issue https://github.com/o19s/quepid/issues/272 before there is a fix. The root cause of this issue is that mousemove event gets triggered first when user clicks the toggle and moves the mouse a little bit. In that case, angular.copy() gets called to save the original order of the query list. However, when the case is big, the cpu usage goes pretty high which causes the UI hanging issue. Suggesting to change the implementation of angular.copy() to async to fix it.

## How Has This Been Tested?

Manually created local docker images with true/false flag and did some smoke tests.

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by epugh** [comment]
Thank you for this PR!   Really great piece of debugging of a hard problem.   @binarymax would this solve your issue?

I think my only hesitation with this fix is that it isn't ideal from an end user perspective!  You don't know you will have the problem till you actually run into it...   And then you are annoyed that Quepid broke, until you read enough docs, ask enoguh questions to find this magic setting that "fixes" it ;-)

Here are some alternatives that I see, ordered in my general preference:

1) Can we do some stuff to solve this performance issue?  Solve the root cause?   This would be ideal, though if it requires us to rebuild the front end or really hack Angular, then maybe not viable.


2) Could we identify at runtime when this problem is happening and just pop a message "drag and drop reordering disabled due to number of queries"...?

3) Do we have any sense of how many queries in a case are required to trigger this bug to happen?   We could look to have the sorting capability disable when you reach a certain number of queries in a case.   Honestly, I find the sorting of queries to be very useful in a small case, where I am sorting on the same page.  Once I start paginating, well, we don't support sorting across pages of queries...   We could just gray out the feature with maybe a message?

**Comment by LiuCao0614** [comment]
Yes, like I said this is just a workaround before we find the permanent fix. I think it would be great if we can have this into the next release, so that we can at least set the configuration on our end and avoid the hanging issue.

**Comment by DmitryKey** [comment]
Hey, I've noticed the following link leads to 404: http://quepid-pr-302.herokuapp.com/cases
Screenshot 2021-03-27 at 12 06 32

**Comment by epugh** [comment]
I get in the console instead of /cases, a empty page, and I see this.  I am going to investigate.   Tahnks @DmitryKey  

```
Possibly unhandled rejection: {"data":{"status":500,"error":"Internal Server Error"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/users/current","headers":{"Accept":"application/json, text/plain, */*","If-Modified-Since":"0","X-CSRF-TOKEN":"qz7yGi58WjEppM0z9HfrjLtGkSJghs7xcJlnRV0MMdpgiyYiv/lThMmHQ1onwoQj8Db4sR/sspwtzs6EQGQEog==","X-Requested-With":"XMLHttpRequest"}},"statusText":"Internal Server Error","xhrStatus":"complete"}
```

**Comment by epugh** [comment]
Okay, so I think this error is misleading, its because we changed the schema to remove the soft delete function, and since allr eview apps share the staging database, this branch doesn't have that!  hence the error. 

However, i tried on http://quepid-staging.herokuapp.com/case/ which has latest code/latest schema, and it gives an error

**Comment by epugh** [comment]
Btw @LiuCao0614 @worleydl I'd like to cut a new Prod Docker release, and I think this is bascially the only ticket we should wait for at this point.   So if we get this to a mergable state, then I'll cut the new version.

**Comment by LiuCao0614** [comment]
@epugh @worleydl Please let me know if you have any updates on this change. Thanks!

**Comment by worleydl** [comment]
Hey Liu,

We're looking to see if there's a fix that addresses the broken code instead of turning it off.  Still aiming to have something ready this week.

Thanks

**Comment by LiuCao0614** [comment]
Hey Dan,

Would it make sense to have this change in first and roll it back after we find a permanent fix? It would be great if we can have a way to bypass the hanging issue at this point.


-Liu

**Comment by LiuCao0614** [comment]
Hey Eric & Dan,

Could you please take a look this mr and merge this in this week if possible? If would be great if we can update our Quepid running in aws cluster.


Thanks,
Liu

**Pull request merged**
