### PR TITLE
Feature/context path support

### PR DESCRIPTION
**Pull request by worleydl**
Adds ability to host quepid behind a context path by specifying `RAILS_RELATIVE_URL_ROOT` ENV var.

## Description
Modify rails config and angular services to utilize relative URL setting.

## Motivation and Context
Orgs with traffic manager setup need a context path to setup routing rules.

## How Has This Been Tested?
Manually so far

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by worleydl** [comment]
I'm okay with the current injects.  I may be building out the config service some more so I think it's okay to live by itself.

**Comment by epugh** [comment]
Works for me ;-).    What are your thoughts on timeline for another release?  Are you looking for "ASAP", so like Monday?   Or do you have some other things you'd like to see baaked in before we release again?

**Comment by epugh** [comment]
@risdenk @worleydl I've seen now two teams that need this solution, so while I know it makes url's being formatted more complex, I'm inclined to live with that!   I'll leave this open for another day or so for a strong countervailing opinion.

**Comment by epugh** [comment]
@worleydl can you add a bit o' docs to https://github.com/o19s/quepid/blob/master/docs/operating_documentation.md about this feature?

**Comment by epugh** [comment]
@worleydl is this still something you want merged?

**Comment by epugh** [comment]
So...    I am faced with this again, and looking at https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root

**Pull request merged**
