### PR TITLE
Added support for Elasticcloud

### PR DESCRIPTION
**Pull request by aditya-kanekar**
- Added Option to select ElasticCloud
- Added option to enter API Key

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] Improvement (non-breaking change which improves existing functionality)
- [] New feature (non-breaking change which adds new functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by worleydl** [comment]
Thanks Aditya, I'm looking thru your changes to Splainer and Quepid now.  Are you okay if I push changes out to your branches or would you like me to create them separately?

**Comment by aditya-kanekar** [comment]
Hello Daniel,You can push it to my branches.Thanks,AdityaSent from my iPhoneOn Oct 5, 2022, at 4:30 PM, Daniel Worley ***@***.***> wrote:﻿
Thanks Aditya, I'm looking thru your changes to Splainer and Quepid now.  Are you okay if I push changes out to your branches or would you like me to create them separately?

**Comment by epugh** [comment]
This branch was continued forward as #566 and has been merged into Quepid!

**Comment by epugh** [comment]
I'm going to close this PR, as the work was merged in the 6.13.0 which is live!   Thank you so much for making this happen @aditya-kanekar!

**Pull request closed without merging**
